[tox]
envlist = py313, py314
skip_missing_interpreters = true

[testenv]
description = Run tests and linting
deps =
    uv
commands =
    uv sync
    uv run ruff check
    uv run ruff format --check
    uv run ty check
    uv run pytest --cov src --cov-report term-missing --durations 10

[testenv:lint]
description = Run linting only
commands =
    uv sync
    uv run ruff check
    uv run ruff format --check
    uv run ty check

[testenv:test]
description = Run tests only
commands =
    uv sync
    uv run pytest --cov src --cov-report term-missing --durations 10
